baseURL = 'https://sanghasanya.com/'
languageCode = 'es-es'
title = 'Sangha Sanya'
theme = 'graysx-hugo'
defaultContentLanguage = 'es'



## Site Settings
[params]
#logo = "assets/img/logo.webp"
logo = "assets/img/vesica_piscis_v3.png"
#favicon = "assets/favicon.png"
favicon = "assets/img/vesica_piscis_v3.png"


# Info
address = "Palma, Islas Baleares"
email = "hola@sanghasanya.com"
phone = "+34 655384230"

# Socials

#twitter = "#"
#facebook = "#"
#instagram = "https://github.com/akatiggerx04/graysx-hugo"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "Nosotros"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Proyectos"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contacto"
  URL = "#signup"
  weight = 3
